version: "3.4"

services:
  # Publishes crypto data to kafka
  crypto-publisher:
    # ./gradlew kafka-publisher:dockerBuildImage
    image: deephaven/crypto-publisher:local-build
    environment:
      JAVA_TOOL_OPTIONS: -Xmx4g
      DEEPHAVEN_BOOTSTRAP_SERVERS: redpanda:9092
      DEEPHAVEN_SCHEMA_REGISTRY_URL: http://redpanda:8081
    depends_on:
      - redpanda
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4500M
        reservations:
          memory: 1000M

  # Consumes crypto data from kafka
  grpc-api:
    # ./gradlew kafka-consumer:buildDocker
    # An extension of grpc-api
    image: deephaven/crypto-consumer:local-build
    environment:
      JAVA_TOOL_OPTIONS: -Xmx4g -Ddeephaven.console.type=python -Ddeephaven.application.dir=/app.d
      DEEPHAVEN_BOOTSTRAP_SERVERS: redpanda:9092
      DEEPHAVEN_SCHEMA_REGISTRY_URL: http://redpanda:8081
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4500M
        reservations:
          memory: 1000M
    depends_on:
      - redpanda
    volumes:
      - data:/data
      - cache:/cache

  web:
    # ./gradlew kafka-web:buildDocker
    # An extension of web
    image: deephaven/crypto-web-app:local-build
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    volumes:
      - web-tmp:/tmp

  redpanda:
    image: deephaven/redpanda:local-build
    volumes:
      - redpanda:/var/lib/redpanda/data

  grpc-proxy:
    image: deephaven/grpc-proxy:local-build
    environment:
      - BACKEND_ADDR=grpc-api:8080
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    depends_on:
      - grpc-api

  envoy:
    # A reverse proxy configured for no SSL on localhost. It fronts the requests
    # for the static content and the websocket proxy.
    image: deephaven/envoy:local-build
    ports:
      - "10042:10000"

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    depends_on:
      - web
      - grpc-proxy
      - grpc-api

volumes:
  redpanda:
  data:
  web-tmp:
  cache: