version: "3.8"

services:
  publisher:
    image: ghcr.io/deephaven-examples/crypto-application-publisher:${TAG}
    environment:
      DEEPHAVEN_BOOTSTRAP_SERVERS: redpanda:9092
      DEEPHAVEN_SCHEMA_REGISTRY_URL: http://redpanda:8081
    depends_on:
      - redpanda

  server:
    image: ghcr.io/deephaven-examples/crypto-application-server:${TAG}
    environment:
      JAVA_TOOL_OPTIONS: -Xmx4g -Ddeephaven.console.type=python -Ddeephaven.application.dir=/app.d
      DEEPHAVEN_BOOTSTRAP_SERVERS: redpanda:9092
      DEEPHAVEN_SCHEMA_REGISTRY_URL: http://redpanda:8081
    depends_on:
      - redpanda
    volumes:
      - data:/data
      - cache:/cache

  web:
    image: ghcr.io/deephaven-examples/crypto-application-web:${TAG}
    volumes:
      - web-tmp:/tmp

  redpanda:
    image: ghcr.io/deephaven-examples/crypto-application-redpanda:${TAG}
    volumes:
      - redpanda:/var/lib/redpanda/data

  grpc-proxy:
    image: deephaven/grpc-proxy:local-build
    environment:
      - BACKEND_ADDR=server:8080
    depends_on:
      server:
        condition: service_healthy

  envoy:
    image: deephaven/envoy:local-build
    ports:
      - "${PORT}:10000"
    depends_on:
      server:
        condition: service_healthy
      grpc-proxy:
        condition: service_started
      web:
        condition: service_started

  client:
    image: ghcr.io/deephaven-examples/crypto-application-client:${TAG}
    environment:
      DEEPHAVEN_SERVER: server:8080
    depends_on:
      server:
        condition: service_healthy
      publisher:
        condition: service_started
    profiles:
      - donotstart

volumes:
  redpanda:
  data:
  web-tmp:
  cache: