version: "3.4"

services:
  crypto-publisher:
    image: ghcr.io/devinrsmith/crypto-publisher:latest
    environment:
      JAVA_TOOL_OPTIONS: -Xmx4g
      DEEPHAVEN_BOOTSTRAP_SERVERS: redpanda:9092
      DEEPHAVEN_SCHEMA_REGISTRY_URL: http://redpanda:8081
    depends_on:
      - redpanda
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4500M
        reservations:
          memory: 1000M

  grpc-api:
    image: ghcr.io/devinrsmith/crypto-consumer:latest
    environment:
      JAVA_TOOL_OPTIONS: -Xmx4g -Ddeephaven.console.type=python -Ddeephaven.application.dir=/app.d
      DEEPHAVEN_BOOTSTRAP_SERVERS: redpanda:9092
      DEEPHAVEN_SCHEMA_REGISTRY_URL: http://redpanda:8081
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4500M
        reservations:
          memory: 1000M
    depends_on:
      - redpanda
    volumes:
      - data:/data
      - cache:/cache

  web:
    image: ghcr.io/devinrsmith/crypto-web-app:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    volumes:
      - web-tmp:/tmp

  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:v21.8.2
    volumes:
      - redpanda:/var/lib/redpanda/data
    expose:
      - 8081
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092

  grpc-proxy:
    image: ghcr.io/deephaven/grpc-proxy:0.5.0
    environment:
      - BACKEND_ADDR=grpc-api:8080
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    depends_on:
      - grpc-api

  envoy:
    image: ghcr.io/deephaven/envoy:0.5.0
    ports:
      - "10042:10000"

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    depends_on:
      - web
      - grpc-proxy
      - grpc-api

volumes:
  redpanda:
  data:
  web-tmp:
  cache: